import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: "#FFFFFF" },
  header: { flexDirection: "row", alignItems: "center", paddingTop: 60, paddingHorizontal: 24 },
  backButton: { marginRight: 16 },
  title: { fontSize: 24, fontWeight: "700", color: "#111827" },
  stepper: { flexDirection: "row", justifyContent: "center", marginVertical: 20 },
  stepText: { fontSize: 16, color: "#333" },
  sectionTitle: { fontSize: 18, fontWeight: "600", color: "#374151", marginBottom: 16 },
  userTypeContainer: { paddingHorizontal: 24, marginBottom: 32 },
  userTypeButtons: { flexDirection: "row", gap: 16 },
  userTypeButton: {
    flex: 1,
    backgroundColor: "#F9FAFB",
    paddingVertical: 20,
    borderRadius: 12,
    alignItems: "center",
    borderWidth: 2,
    borderColor: "#E5E7EB",
  },
  userTypeButtonActive: { backgroundColor: "#2563EB", borderColor: "#2563EB" },
  userTypeText: { fontSize: 16, fontWeight: "600", color: "#6B7280", marginTop: 8 },
  userTypeTextActive: { color: "#FFFFFF" },
  form: { paddingHorizontal: 24, gap: 16 },
  input: {
    backgroundColor: "#F9FAFB",
    borderWidth: 1,
    borderColor: "#E5E7EB",
    borderRadius: 12,
    paddingHorizontal: 16,
    paddingVertical: 14,
    fontSize: 16,
  },
  fileButton: {
    backgroundColor: "#007bff",
    paddingVertical: 10,
    paddingHorizontal: 20,
    borderRadius: 8,
    alignItems: "center",
    marginTop: 10,
  },
  previewImage: {
    width: 150,
    height: 150,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: "#ccc",
  },
  navigation: {
    paddingHorizontal: 24,
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginVertical: 20,
  },
  backBtn: {
    backgroundColor: "#ccc",
    paddingVertical: 10,
    paddingHorizontal: 20,
    borderRadius: 8,
  },
  nextBtn: {
    backgroundColor: "#007bff",
    paddingVertical: 10,
    paddingHorizontal: 20,
    borderRadius: 8,
  },
  finishBtn: {
    backgroundColor: "green",
    paddingVertical: 10,
    paddingHorizontal: 20,
    borderRadius: 8,
  },
  subtitle: { textAlign: "center", color: "#6B7280", marginBottom: 10 },
  codeContainer: {
    flexDirection: "row",
    justifyContent: "space-between",
    width: "100%",
    marginTop: 10,
  },
  codeInput: {
    borderWidth: 1,
    borderColor: "#D1D5DB",
    borderRadius: 8,
    width: 45,
    height: 50,
    textAlign: "center",
    fontSize: 18,
    color: "#111827",
  },
});